# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9860c52ddc92ab389ca663832ac92d4e"
name = "simple"
handle = "simple-29"
application_url = "https://simple-shopify-app.azurewebsites.net"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = ["https://simple-shopify-app.azurewebsites.net/auth/callback", "https://simple-shopify-app.azurewebsites.net/auth/shopify/callback", "https://simple-shopify-app.azurewebsites.net/api/auth/callback"]

[pos]
embedded = false